---
title: "Intro_eletrofisiologia"
author: "Amanda Yumi"
date: "30 de setembro de 2018"
output: html_document
weight: 5
---

# Eletrofiosiologia

   * 1929 - Hans Berger queria medir telepatia em humanos pela primeira vez: Como um soldado no exército alemão na primeira década de 1900, Hans Berger caiu de seu cavalo em frente de um carro de artilharia e quase foi atropelado. Quando ele voltou para o quartel, havia um telegrama de seu pai dizendo que sua irmã teve a “sensação” de que ele tinha sido ferido. Com essa motivação, Berger quis explorar manifestações físicas dessas transmissões psíquicas \citep{evans1999introduction}
    * 1935 - Hallowell e Pauline Davis obtêm os primeiros registros de ERPs (potencial evocado).
    * 1964 - Gray Walter reporta o primeiro componente cognitivo de ERP - era moderna da técnica
    * 1964 - Sutton, Braren, Zubin e John descobrem o P300
    * 1960: ERPlogy: estudo dos componentes do ERP
    * 1980: Ressurgimento devido à popularização dos computadores